#!/bin/bash
. ../../scripts/debug.bash
declare -A counttests
tests=( \
    ./smart \
    ./module-1.mk \
    ./module-2.mk \
    ./module-3.mk \
    )
lines=($(smart TOOL=test))
if (( ${#tests[@]} != ${#lines[@]} )); then
    error "${#tests[@]} != ${#lines[@]}"
fi
for ((i=0; i < ${#lines[@]}; ++i)); {
    line=${lines[i]}
    counttests[$line]=$((${counttests[$line]}+1))
}
for ((i=0; i < ${#tests[@]}; ++i)); {
    test=${tests[i]}
    if ((${counttests[$test]} != 1)); then
	error "$test (${counttests[$test]})"
    fi
}
for ((i=0; i < ${#tests[@]}; ++i)); {
    test=${tests[i]}
    s=$(smart TOOL=test module-$test)
    if [[ "x$test" != "x$s" ]]; then
	info "$test: $s"
    fi
}
