#!/bin/bash
tests=( \
    gcc \
    )
for ((i=0; i < ${#tests[@]}; ++i)); {
    cd ${tests[i]}
    echo "test: Entering directory \`${tests[i]}'"
    ./run
    echo "test: Leaving directory \`${tests[i]}'"
    cd - > /dev/null
}
