#!/bin/bash
source ../scripts/source/debug.bash

function is-subset-of ()
{
    if [[ "x$1" != "x" ]]; then
	eval "local a1=( \"\${$1[@]}\" )"
    else
	local a1=()
    fi
    if [[ "x$2" != "x" ]]; then
	eval "local a2=( \"\${$2[@]}\" )"
    else
	local a2=()
    fi

    local same=yes
    for ((i=0; i < ${#a1[@]}; ++i)) {
	local found=no
	for ((j=0; j < ${#a2[@]}; ++j)) {
	    if [[ "x${a1[$i]}" == "x${a2[$j]}" ]]; then
		found=yes
		break
	    fi
	}

	if [[ "x$found" != "xyes" ]]; then
	    same=no
	    break
	fi
    }

    [[ "x$same" == "xyes" ]]
}

function is-same-set ()
{
    if [[ "x$1" != "x" ]]; then
	eval "local n1=( \"\${#$1[@]}\" )"
    else
	local n1=0
    fi
    if [[ "x$2" != "x" ]]; then
	eval "local n2=( \"\${#$2[@]}\" )"
    else
	local n2=0
    fi

    if (( $n1 != $n2 )); then
	false
    else
	is-subset-of $1 $2
    fi
}

function check-same-array ()
{
    if [[ "x$1" != "x" ]]; then
	eval "local a1=( \"\${$1[@]}\" )"
    else
	local a1=()
    fi
    if [[ "x$2" != "x" ]]; then
	eval "local a2=( \"\${$2[@]}\" )"
    else
	local a2=()
    fi

    if [[ ${#a1[@]} != ${#a2[@]} ]]; then
	error -1 "length not equal: ${#a1[@]} != ${#a2[@]}"
    fi

    function l () { printf "\n"; }

    for ((i=0; i < ${#a1[@]}; ++i)) {
	if [[ "x${a1[$i]}" != "x${a2[$i]}" ]]; then
	    info -1 "line $i: ${a1[$i]}"
	    info -1 "line $i: ${a2[$i]}"
	    error -1 "line $i not same!"
	fi
    }
}

function check-files ()
{
    eval "local files=( \"\${$1[@]}\" )"
    for file in ${files[@]}; do
	[[ -f $file ]] || error -1 "$file not found"
    done
}

function check-dirs ()
{
    eval "local dirs=( \"\${$1[@]}\" )"
    for d in ${dirs[@]}; do
	[[ -d $d ]] || error -1 "$d not found"
    done
}

function check-program-result ()
{
    local s r
    s=$($1)
    r=$?
    [[ "x$r" == "x$2" ]] || error -1 "$r != $2"
    [[ "x$s" == "x$3" ]] || error -1 "$s != $3"
}

function ensure-internal-test-utilities ()
{
    local a1=()
    local a2=()

    a1=(1 2 3)
    a2=(1 2 3)
    is-subset-of a1 a2 || error "is-subset-of not working"
    is-same-set  a1 a2 || error "is-same-set not working"
    check-same-array a1 a2

    a1=(1 2 3)
    a2=(1 a 2 b 3)
    is-subset-of a1 a2 || error "is-subset-of not working"
    is-same-set  a1 a2 && error "is-same-set not working"

    a1=(1 a 2 b 3)
    a2=(1 2 3)
    is-subset-of a1 a2 && error "is-subset-of not working"
    is-same-set  a1 a2 && error "is-same-set not working"

    check-program-result "echo foo" 0 "foo"
}

function run-tests ()
{
    local tests=( "$@" )
    for ((i=0; i < ${#tests[@]}; ++i)); {
	(
	    source "$PWD/${tests[i]}/run" && (
		echo "test: Entering directory \`$PWD/${tests[i]}'"
		cd "${tests[i]}"
		( run )
		cd - > /dev/null
		echo "test: Leaving directory \`$PWD/${tests[i]}'"
	    )
	)
    }
}

ensure-internal-test-utilities

run-tests \
    tools

    # modules \
    # targets \
    # tree \
    # requires \
    # tools \
