#
#    Copyright (C) 2012, 2013, Duzy Chan <code@duzy.info>.
#    
#    All rights reserved.
#
$(smart.internal)

#$(LIBS.jar:$(OUT)/%=$(TOP)/$(OUT)/%)
$(OUT)/$(NAME)/proguard.cfg: proguard := $(PROGUARD)
$(OUT)/$(NAME)/proguard.cfg: proguards.res := res.proguard $(RES.proguard)
$(OUT)/$(NAME)/proguard.cfg: classes := $(LIBS.classes:$(OUT)/%=$(TOP)/$(OUT)/%)
$(OUT)/$(NAME)/proguard.cfg: classes += classes
$(OUT)/$(NAME)/proguard.cfg: libs := $(ANDROID_PLATFORM_LIB)
$(OUT)/$(NAME)/proguard.cfg: libs += $(filter-out $(LIBS.classes:%=%.jar),$(LIBS.jar))
$(OUT)/$(NAME)/proguard.cfg: $(SCRIPT)
	@mkdir -p $(@D)
	@echo "# Generated by smart-make, don't edit me!" > $@
	@echo "# Edit '$(proguard)' instead!" >> $@
	@for L in $(libs); do echo "-libraryjars $$L" ; done >> $@
	@for L in $(classes); do echo "-injars $$L" ; done >> $@
	@echo "-outjars classes-obfuscated.jar" >> $@
	@echo "-printmapping classes-obfuscated.map" >> $@
	@for L in $(proguards.res); do echo "-include $$L" ; done >> $@
	@echo "-include ../../$(proguard)" >> $@

$(OUT)/$(NAME)/classes-obfuscated.jar: proguard := $(ANDROID.proguard)/lib/proguard.jar
$(OUT)/$(NAME)/classes-obfuscated.jar: proguard_cfg := $(OUT)/$(NAME)/proguard.cfg
$(OUT)/$(NAME)/classes-obfuscated.jar: $(OUT)/$(NAME)/res.proguard
$(OUT)/$(NAME)/classes-obfuscated.jar: $(OUT)/$(NAME)/proguard.cfg
$(OUT)/$(NAME)/classes-obfuscated.jar: $(OUT)/$(NAME)/.classes
$(OUT)/$(NAME)/classes-obfuscated.jar: $(PROGUARD)
	@java -jar $(proguard) @$(proguard_cfg)
