#
#    Copyright (C) 2012, 2013, Duzy Chan <code@duzy.info>.
#    
#    All rights reserved.
#
$(smart.internal)

$(OUT)/$(NAME)/proguard.cfg: proguard := $(PROGUARD)
$(OUT)/$(NAME)/proguard.cfg: proguards.res := $(RES.proguard)
$(OUT)/$(NAME)/proguard.cfg: libs := $(LIBS.java) $(ANDROID_PLATFORM_LIB)
$(OUT)/$(NAME)/proguard.cfg: $(SCRIPT)
	@mkdir -p $(@D)
	@echo "# Generated by smart-make, don't edit me!" > $@
	@echo "# Edit '$(proguard)' instead!" >> $@
	@for L in $(libs); do echo "-libraryjars $$L" ; done >> $@
	@echo "-injars classes" >> $@
	@echo "-outjars classes-obfuscated.jar" >> $@
	@echo "-printmapping classes-obfuscated.map" >> $@
	@echo "-include res.proguard" >> $@
	@for L in $(proguards.res); do echo "-include $$L" ; done >> $@
	@echo "-include ../../$(proguard)" >> $@

$(OUT)/$(NAME)/classes-obfuscated.jar: proguard := $(ANDROID.proguard)/lib/proguard.jar
$(OUT)/$(NAME)/classes-obfuscated.jar: proguard_cfg := $(OUT)/$(NAME)/proguard.cfg
$(OUT)/$(NAME)/classes-obfuscated.jar: $(OUT)/$(NAME)/res.proguard
$(OUT)/$(NAME)/classes-obfuscated.jar: $(OUT)/$(NAME)/proguard.cfg
$(OUT)/$(NAME)/classes-obfuscated.jar: $(OUT)/$(NAME)/.classes
$(OUT)/$(NAME)/classes-obfuscated.jar: $(PROGUARD)
	@java -jar $(proguard) @$(proguard_cfg)
