#!/bin/bash
. ../../scripts/debug.bash
declare -A counttests
tests=( \
    ./smart \
    ./leaf-1/smart \
    ./leaf-1/leaf-1-1/smart \
    ./leaf-1/leaf-1-1/leaf-1-1-1/smart \
    ./leaf-1/leaf-1-1/leaf-1-1-2/smart \
    ./leaf-1/leaf-1-1/leaf-1-1-3/smart \
    ./leaf-1/leaf-1-2/smart \
    ./leaf-1/leaf-1-2/leaf-1-2-1/smart \
    ./leaf-1/leaf-1-2/leaf-1-2-2/smart \
    ./leaf-1/leaf-1-2/leaf-1-2-2/leaf-1-2-2-1/smart \
    ./leaf-1/leaf-1-2/leaf-1-2-2/leaf-1-2-2-2/smart \
    ./leaf-1/leaf-1-2/leaf-1-2-2/leaf-1-2-2-3/smart \
    ./leaf-1/leaf-1-2/leaf-1-2-3/smart \
    ./leaf-1/leaf-1-3/smart \
    ./leaf-2/smart \
    ./leaf-2/leaf-2-1/smart \
    ./leaf-2/leaf-2-2/smart \
    ./leaf-2/leaf-2-3/smart \
    ./leaf-3/smart \
    ./leaf-3/leaf-3-1/smart \
    ./leaf-3/leaf-3-2/smart \
    ./leaf-3/leaf-3-3/smart \
    )
lines=($(smart TOOL=test))
if (( ${#tests[@]} != ${#lines[@]} )); then
    error a
fi
for ((i=0; i < ${#lines[@]}; ++i)); {
    line=${lines[i]}
    counttests[$line]=$((${counttests[$line]}+1))
}
for ((i=0; i < ${#tests[@]}; ++i)); {
    test=${tests[i]}
    if ((${counttests[$test]} != 1)); then
	error "$test (${counttests[$test]})"
    fi
}
for ((i=0; i < ${#tests[@]}; ++i)); {
    test=${tests[i]}
    s=$(smart TOOL=test module-$test)
    if [[ "x$test" != "x$s" ]]; then
	info "$test: $s"
    fi
}
