#if 0
#include <algorithm>
#include <assert.h>
#include <bitset>
#include <cassert>
#include <cctype>
#include <cerrno>
#include <cfloat>
#include <ciso646>
#include <climits>
#include <clocale>
#include <cmath>
#include <complex>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <ctype.h>
#include <cwchar>
#include <cwctype>
#include <deque>
#include <errno.h>
#include <exception>
#include <exception.h>
#include <float.h>
#include <fstream>
#include <fstream.h>
#include <functional>
#include <hash_map>
#include <hash_set>
#include <iomanip>
#include <iomanip.h>
#include <ios>
#include <iosfwd>
#include <ios.h>
#include <iostream>
#include <iostream.h>
#include <iso646.h>
#include <istream>
#include <istream.h>
#include <iterator>
#include <limits>
#include <limits.h>
#include <list>
#include <locale>
#include <locale.h>
#include <map>
#include <math.h>
#include <mem.h>
#include <memory>
#include <new>
#include <new.h>
#include <numeric>
#include <ostream>
#include <ostream.h>
#include <pthread_alloc>
#include <pthread.h>
#include <queue>
#include <rlocks.h>
#include <rope>
#include <set>
#include <setjmp.h>
#include <signal.h>
#include <slist>
#include <sstream>
#include <stack>
#include <stdarg.h>
#include <stddef.h>
#include <stdexcept>
#include <stdio.h>
#include <stdiostream.h>
#include <stdlib.h>
#include <streambuf>
#include <streambuf.h>
#include <string>
#include <string.h>
#include <strstream>
#include <strstream.h>
#include <time.h>
#include <typeinfo>
#include <typeinfo.h>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <valarray>
#include <vector>
#include <wchar.h>
#include <wctype.h>

#include <stl/_abbrevs.h>
#include <stl/_algobase.c>
#include <stl/_algobase.h>
#include <stl/_algo.c>
#include <stl/_algo.h>
#include <stl/_alloc.c>
#include <stl/_alloc.h>
#include <stl/_auto_ptr.h>
#include <stl/_bitset.c>
#include <stl/_bitset.h>
#include <stl/boost_type_traits.h>
#include <stl/_bvector.h>
#include <stl/_carray.h>
#include <stl/_cctype.h>
#include <stl/char_traits.h>
#include <stl/_clocale.h>
#include <stl/c_locale.h>
#include <stl/_cmath.h>
#include <stl/_codecvt.h>
#include <stl/_collate.h>
#include <stl/_complex.c>
#include <stl/_complex.h>
#include <stl/concept_checks.h>
#include <stl/config>
#include <stl/_config_compat_post.h>
#include <stl/_construct.h>
#include <stl/_cprolog.h>
#include <stl/_csetjmp.h>
#include <stl/_csignal.h>
#include <stl/_cstdarg.h>
#include <stl/_cstddef.h>
#include <stl/_cstdio.h>
#include <stl/_cstdlib.h>
#include <stl/_cstring.h>
#include <stl/_ctime.h>
#include <stl/_ctraits_fns.h>
#include <stl/_ctype.h>
#include <stl/_cwchar.h>
#include <stl/_cwctype.h>
#include <stl/debug>
#include <stl/_deque.c>
#include <stl/_deque.h>
#include <stl/_epilog.h>
#include <stl/_exception.h>
#include <stl/_facets_fwd.h>
#include <stl/_fstream.c>
#include <stl/_fstream.h>
#include <stl/_function_adaptors.h>
#include <stl/_function_base.h>
#include <stl/_function.h>
#include <stl/_hash_fun.h>
#include <stl/_hash_map.h>
#include <stl/_hash_set.h>
#include <stl/_hashtable.c>
#include <stl/_hashtable.h>
#include <stl/_heap.c>
#include <stl/_heap.h>
#include <stl/_iomanip.h>
#include <stl/_ios_base.h>
#include <stl/_ios.c>
#include <stl/_ioserr.h>
#include <stl/_iosfwd.h>
#include <stl/_ios.h>
#include <stl/_iostream_string.h>
#include <stl/_istreambuf_iterator.h>
#include <stl/_istream.c>
#include <stl/_istream.h>
#include <stl/_iterator_base.h>
#include <stl/_iterator.h>
#include <stl/_iterator_old.h>
#include <stl/_limits.c>
#include <stl/_limits.h>
#include <stl/_list.c>
#include <stl/_list.h>
#include <stl/_locale.h>
#include <stl/_map.h>
#include <stl/_mbstate_t.h>
#include <stl/_messages_facets.h>
#include <stl/_monetary.c>
#include <stl/_monetary.h>
#include <stl/_move_construct_fwk.h>
#include <stl/msl_string.h>
#include <stl/_new.h>
#include <stl/_numeric.c>
#include <stl/_numeric.h>
#include <stl/_num_get.c>
#include <stl/_num_get.h>
#include <stl/_numpunct.h>
#include <stl/_num_put.c>
#include <stl/_num_put.h>
#include <stl/_ostreambuf_iterator.h>
#include <stl/_ostream.c>
#include <stl/_ostream.h>
#include <stl/_pair.h>
#include <stl/pointers>
#include <stl/_prolog.h>
#include <stl/_pthread_alloc.h>
#include <stl/_ptrs_specialize.h>
#include <stl/_queue.h>
#include <stl/_range_errors.c>
#include <stl/_range_errors.h>
#include <stl/_raw_storage_iter.h>
#include <stl/_relops_cont.h>
#include <stl/_relops_hash_cont.h>
#include <stl/_rope.c>
#include <stl/_rope.h>
#include <stl/_set.h>
#include <stl/_slist_base.c>
#include <stl/_slist_base.h>
#include <stl/_slist.c>
#include <stl/_slist.h>
#include <stl/_sparc_atomic.h>
#include <stl/_sstream.c>
#include <stl/_sstream.h>
#include <stl/_stack.h>
#include <stl/_stdexcept_base.c>
#include <stl/_stdexcept_base.h>
#include <stl/_stdexcept.h>
#include <stl/_stlport_version.h>
#include <stl/_streambuf.c>
#include <stl/_streambuf.h>
#include <stl/_stream_iterator.h>
#include <stl/_string_base.h>
#include <stl/_string.c>
#include <stl/_string_fwd.h>
#include <stl/_string.h>
#include <stl/_string_hash.h>
#include <stl/_string_io.c>
#include <stl/_string_io.h>
#include <stl/_string_npos.h>
#include <stl/_string_operators.h>
#include <stl/_string_sum.h>
#include <stl/_string_sum_methods.h>
#include <stl/_string_workaround.h>
#include <stl/_strstream.h>
#include <stl/_tempbuf.c>
#include <stl/_tempbuf.h>
#include <stl/_threads.c>
#include <stl/_threads.h>
#include <stl/_time_facets.c>
#include <stl/_time_facets.h>
#include <stl/_tree.c>
#include <stl/_tree.h>
#include <stl/_typeinfo.h>
#include <stl/type_manips.h>
#include <stl/type_traits.h>
#include <stl/_uninitialized.h>
#include <stl/_unordered_map.h>
#include <stl/_unordered_set.h>
#include <stl/_valarray.c>
#include <stl/_valarray.h>
#include <stl/_vector.c>
#include <stl/_vector.h>
#include <using/cstring>
#include <using/export>
#include <using/fstream>
#include <using/h/fstream.h>
#include <using/h/iomanip.h>
#include <using/h/iostream.h>
#include <using/h/ostream.h>
#include <using/h/streambuf.h>
#include <using/h/strstream.h>
#include <using/iomanip>
#include <using/ios>
#include <using/iosfwd>
#include <using/iostream>
#include <using/istream>
#include <using/locale>
#include <using/ostream>
#include <using/sstream>
#include <using/streambuf>
#include <using/strstream>

int main (int argc, char**argv)
{
    {
	std::string s("foo");
	std::cout << s;
    }
    return 0;
}
#else
int main (int argc, char**argv)
{
    return 0;
}
#endif
