NDK_BUILD_TYPE := shared
NDK_BUILD_TARGETS :=
$(foreach 1,$(APP_ABI),$(eval NDK_BUILD_TARGETS += libs/$1/lib$(LOCAL_MODULE:lib%=%).so))

NDK_EXPORT := yes

define smart~export_shared
  $(OUT)/.export/$(NAME)/Android.mk: $(NDK_BUILD_TARGETS:%=$(SRCDIR)/%) \
    $(smart.root)/internal/android/ndkbuild/shared.mk
	@mkdir -p $$(@D)
	@echo "# Generated by smart, don't edit!" > $$@
	@echo 'LOCAL_PATH := $$$$(call my-dir)' >> $$@
	@echo 'include $$$$(CLEAR_VARS)' >> $$@
	@echo 'LOCAL_MODULE := $(LOCAL_MODULE)' >> $$@
	@echo 'LOCAL_SRC_FILES := ../../../$(SRCDIR)/libs/$$$$(TARGET_ARCH_ABI)/lib$$$$(LOCAL_MODULE).so' >> $$@
	@echo 'LOCAL_EXPORT_C_INCLUDES := $(LOCAL_EXPORT_C_INCLUDES:%=$(PWD)/$(SRCDIR)/%)' >> $$@
	@echo 'LOCAL_EXPORT_LDLIBS := $(LOCAL_EXPORT_LDLIBS)' >> $$@
	@echo 'include $$$$(PREBUILT_SHARED_LIBRARY)' >> $$@
	@echo "exported: $(NAME)/Android.mk"
endef #smart~export_shared
$(eval $(smart~export_shared))
smart~export_shared :=
