#
#    Copyright (C) 2012, 2013, Duzy Chan <code@duzy.info>.
#    All rights reserved.
#
smart.context.mingw := SOURCES PROGRAM LIBRARY \
  CFLAGS CXXFLAGS GOFLAGS ASFLAGS ARFLAGS LDFLAGS LDLIBS \
  FULLLIBS LOADLIBS LIBADD DEFINES INCLUDES \
  INSTALLS INSTALL_PATH TOOLPREFIX \
